apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
spec: 
  destination:
    namespace: gitea-dev
    server: https://kubernetes.default.svc
  project: gitea
  source:
    path: gitea/ 
    repoURL: https://github.com/loydpadgett/gitea_local.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
